connectors:
  matrix:
    # Required
    mxid: "@bot_eventmanager:bot.parsi.ai"
    password: "YekRamzeSakht098"
    rooms:
      'main': '#Team8:bot.parsi.ai'
    # Optional
    homeserver: "https://bot.parsi.ai"
    nick: "NLP_BOT_Team8"  # The nick will be set on startup
    # device_id: "OPSDroid"
    # device_name: "opsdroid"
    enable_encryption: True
skills:
  main_skill:
    path: skills/main_skill.py
  accept_invite:
    path: skills/accept_invite.py
  welcome:
    path: skills/welcome_skill.py

databases:
  sqlite:
    type: sqlite
    file: opsdroid.db

# web:
#   base-url: "https://580d-193-29-107-90.ngrok-free.app"
# connectors:
#     telegram:
#       token: "7095268559:AAE8-6F2wqclDO6MVoXeFuIkWZp4EArQ2nE"
#       reply-unauthorized: True
# skills:
#   main_skill:
#     path: skills/main_skill.py
#   accept_invite:
#     path: skills/accept_invite.py
#   welcome:
#     path: skill/welcome_skill.py

# databases:
#   sqlite:
#     type: sqlite
#     file: opsdroid.db
