# connectors:
#   matrix:
#     # Required
#     mxid: "@bot_ghavi:matrix.org"
#     password: "vHc!D?Eq8sTKASd"
#     rooms:
#       'main': '#Team8:matrix.org'
#     # Optional
#     homeserver: "https://matrix.org"
#     nick: "NLP_BOT_Team8"  # The nick will be set on startup
#     # device_id: "OPSDroid"
#     # device_name: "opsdroid"
#     enable_encryption: True
# skills:
#   main_skill:
#     path: skills/main_skill.py
#   accept_invite:
#     path: skills/accept_invite.py

# databases:
#   sqlite:
#     type: sqlite
#     file: opsdroid.db

web:
  base-url: "https://240a-193-29-107-90.ngrok-free.app"
connectors:
    telegram:
      token: "7095268559:AAE8-6F2wqclDO6MVoXeFuIkWZp4EArQ2nE"
      reply-unauthorized: True
skills:
  main_skill:
    path: skills/main_skill.py
  accept_invite:
    path: skills/accept_invite.py

databases:
  sqlite:
    type: sqlite
    file: opsdroid.db
